WebForum/Models/DB/Posts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebForum.Models.DB
{
    public partial class Posts
    {
        public int PostId { get; set; }
        [Display(Name = "Date")]
        public DateTime? DatePosted { get; set; }
        [Display(Name = "Posts")]
        public string PostDescription { get; set; }
        public int ThreadId { get; set; }
        public int UserAccountId { get; set; }

        public Threads Thread { get; set; }
        public UserAccounts UserAccount { get; set; }
    }
}

WebForum/Models/DB/Threads.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebForum.Models.DB
{
    public partial class Threads
    {
        public Threads()
        {
            Posts = new HashSet<Posts>();
        }

        public int ThreadId { get; set; }
        [Display(Name = "Date")]
        public DateTime? ThreadDate { get; set; }
        public string ThreadTitle { get; set; }
        public int CategoryId { get; set; }
        public int UserAccountId { get; set; }

        public Categories Category { get; set; }
        public UserAccounts UserAccount { get; set; }
        public ICollection<Posts> Posts { get; set; }
    }
}

WebForum/Models/PostsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebForum.Models.DB;

namespace WebForum.Models
{
    public partial class PostsViewModel
    {
        [Key]
        public int key { get; set; }
        public Threads Thread { get; set; }
        public Posts Post { get; set; }
        public UserAccounts UserAccount { get; set; }
    }
}

WebForum/Controllers/ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebForum.Filters;
using WebForum.Models.DB;
using WebForum.Services;

namespace WebForum.Controllers
{
    public class ThreadController : Controller
    {

        private readonly WebForumDBContext _db;
        private UserAccountService userService;
        private DataService dataService;
        private IConfiguration config;

        public ThreadController(WebForumDBContext db, IConfiguration _config)
        {
            _db = db;
            config = _config;
            userService = new UserAccountService(_db, config);
            dataService = new DataService(_db);
        }
        public ActionResult ThreadIndex(int categoryId)
        {
            var threadsList = dataService.GetThreadsInList(categoryId);
            ViewBag.CategoryId = categoryId;
            return View(threadsList);
        }
        public ActionResult Posts(int threadId)
        {
            var postsList = dataService.AddPostsToList(threadId);
            //var postsList = dataService.GetPostsInList(threadId);           
            //var posts = dataService.GetPosts(threadId);
            return View(postsList);
        }

        [Authorize(Roles.USER)]
        public ActionResult Reply(int threadId)
        {
            return View();
        }
        [Authorize(Roles.USER)]
        public ActionResult NewThread(int categoryId)
        {
            ViewBag.CategoryId = categoryId;
            return View();
        }

        [Authorize(Roles.USER)]
        public ActionResult DeletePost(int postId)
        {
            var post = dataService.GetPost(postId);
            var threadId = dataService.GetThreadId(postId);
            var userName = HttpContext.User.Identity.Name;
            var userId = dataService.GetUserIdFromName(userName);
            var userAllowed = dataService.CheckIfPostMadeByUser(userId, postId);

            if (userAllowed != true)
            {
                return RedirectToAction("Posts", new { threadId });
            }
            return View(post);
        }
        [Authorize(Roles.USER)]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePostInDb(IFormCollection collection)
        {
            var postId = Convert.ToInt32(collection["PostId"]);
            var post = dataService.GetPost(postId);
            var threadId = post.ThreadId;
            _db.Posts.Remove(post);
            _db.SaveChanges();
            return RedirectToAction("Posts", new { threadId });
        }

        [Authorize(Roles.USER)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReplyForm(IFormCollection collection)
        {
            var userName = HttpContext.User.Identity.Name;
            var userId = dataService.GetUserIdFromName(userName);
            var post = collection["PostDescription"];
            var threadId = Convert.ToInt32(collection["ThreadId"]);
            var datePosted = DateTime.Now;
            var reply = dataService.PostReply(post, threadId, datePosted, userId);
            var title = dataService.GetThreadTitle(reply.ThreadId);
            using (var transaction = _db.Database.BeginTransaction())
            {
                try
                {
                    _db.Posts.Add(reply); // adds customer entity to DB
                    _db.SaveChanges();
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                }
            }                
            return RedirectToAction("Posts", new { threadId });
        }
        [Authorize(Roles.USER)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThreadForm(IFormCollection collection)
        {
            var userName = HttpContext.User.Identity.Name;
            var userId = dataService.GetUserIdFromName(userName);
            var title = collection["Thread.ThreadTitle"];
            var postDescription = collection["Post.PostDescription"];
            var categoryId = Convert.ToInt32(collection["CategoryId"]);
            var datePosted = DateTime.Now;
            var thread = dataService.NewThread(title, categoryId, datePosted, userId);
            using (var transaction = _db.Database.BeginTransaction())
            {
                try
                {
                    _db.Threads.Add(thread);
                    _db.SaveChanges();
                    var threadId = dataService.GetThreadId(title);
                    var post = dataService.PostReply(postDescription, threadId, datePosted, userId);
                    _db.Posts.Add(post);
                    _db.SaveChanges();
                    //var userName = HttpContext.User.Identity.Name;
                    //var userId = dataService.GetUserIdFromName(userName);
                    //var userThreadBridge = dataService.UserThreadBridgeUpdate(threadId, userId);
                    //_db.SaveChanges();
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                }                
            }            
            return RedirectToAction("ThreadIndex", new { categoryId });
        }
        // POST: Categories/Create       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string category)
        {

            return View();
        }
        [Authorize(Roles.USER)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostForm(IFormCollection collection)
        {

            return View();
        }

    }
}

WebForum/Views/Thread/DeletePost.cshtml
@model WebForum.Models.DB.Posts

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePosted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thread.ThreadId)
        </dd>
        <dd>
            @using (Html.BeginForm("DeletePostInDb", "Thread", FormMethod.Post))
            {
                @Html.HiddenFor(model => model.PostId)
                <input type="submit" value="Delete Post?" />
            }
            @*@Html.ActionLink("Delete Post?", "DeletePostInDb", "Thread", new { postId = Model.PostId }, new { @class = "btn btn-default" })*@ @*VAR FÖR FUNKAR INTE URL PARAMETER ROUTEN??*@
        </dd>
    </dl>
   


</div>

WebForum/Views/Thread/NewThread.cshtml
@model WebForum.Models.DB.NewThreadModel
@{
    int CategoryId = Convert.ToInt32(ViewBag.CategoryId); 
}
<h1>
    New Thread
</h1>

@using (Html.BeginForm("ThreadForm", "Thread", FormMethod.Post))
{
    <table cellpadding="2" cellspacing="2">
        <tr>
            <td>Reply</td>
            <td>
                @Html.TextBoxFor(c => c.Thread.ThreadTitle)
            </td>
            <td>
                @Html.TextAreaFor(m => m.Post.PostDescription)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Hidden("CategoryId", CategoryId)

            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Post" /></td>
        </tr>
    </table>
}

    <div>
        <a asp-action="Index" asp-controller="Home">Back to Home</a>
    </div>


WebForum/Views/Thread/Posts.cshtml
@model IEnumerable<WebForum.Models.PostsViewModel>

<h1>
    Posts
</h1>


<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="col-sm-3">
                    @Html.DisplayFor(m => item.Post.PostDescription)
                </td>
                <td>
                    Posted by: @Html.DisplayFor(m => item.UserAccount.AccountName)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Post.DatePosted)
                </td>
                <td>
                    @Html.ActionLink("Reply", "Reply", "Thread", new { threadId = item.Post.ThreadId }, new { @class = "btn btn-default" })
                </td>
                <td>
                    @Html.ActionLink("Delete Post", "DeletePost", "Thread", new { postId = item.Post.PostId, threadId = item.Post.ThreadId }, new { @class = "btn btn-default" })
                </td>
            </tr>
        }

    </tbody>
</table>



WebForum/Views/Thread/Reply.cshtml
@model WebForum.Models.DB.Posts

<h1>
    Reply
</h1>

<hr />
<div class="row">
    <div class="col-md-4">

            @using (Html.BeginForm("ReplyForm", "Thread", FormMethod.Post))
            {
                <table cellpadding="2" cellspacing="2">
                    <tr>
                        <td>Reply</td>
                        <td>
                            @Html.TextAreaFor(m => m.PostDescription)
                        </td>
                    </tr>                  
                    <tr>
                        <td>
                            @Html.HiddenFor(m => m.ThreadId)
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Reply" /></td>
                    </tr>
                </table>
            }

    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to Home</a>
</div>


WebForum/Views/Thread/ThreadIndex.cshtml
@model IEnumerable<WebForum.Models.DB.Threads>

<h1>
    Threads
</h1>
            @{ 
                var catId = ViewBag.CategoryId;
            }
                        

<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.ThreadTitle, "Posts", "Thread", new { threadId = item.ThreadId})
                </td>
            </tr>            

        }
    </tbody>

    <tfoot>
        <tr>
            <td>               
                @Html.ActionLink("New Thread", "NewThread", "Thread", new { categoryId = catId }, new { @class = "btn btn-default" })
            </td>
        </tr>
    </tfoot>
</table>